<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>NotesForSublime</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'|\n</string>
			<key>name</key>
			<string>entity.other</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)|\n</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\*</string>
			<key>end</key>
			<string>\*|\n</string>
			<key>name</key>
			<string>variable</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\/</string>
			<key>end</key>
			<string>\/|\n</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\!</string>
			<key>end</key>
			<string>\!|\n</string>
			<key>name</key>
			<string>constant.escape</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\-</string>
			<key>end</key>
			<string>\-|\n</string>
			<key>name</key>
			<string>string.quoted.double.NotesForSublime</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]|\n</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}|\n</string>
			<key>name</key>
        	<string>support</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\|</string>
			<key>end</key>
			<string>\||\n</string>
			<key>name</key>
        	<string>storage</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#</string>
			<key>end</key>
			<string>\#|\n</string>
			<key>name</key>
        	<string>entity.other.inherited-class</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\?</string>
			<key>end</key>
			<string>\?|\n</string>
			<key>name</key>
        	<string>invalid.deprecated</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.NotesForSublime</string>
	<key>uuid</key>
	<string>FB7889E9-6E33-497E-BCF8-91860D0993B</string>
</dict>
</plist>
